//go:build !ignore_autogenerated_core_v1alpha4
// +build !ignore_autogenerated_core_v1alpha4

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen-v0.22.2. DO NOT EDIT.

package v1alpha4

import (
	unsafe "unsafe"

	v1beta1 "github.com/TencentCloud/cluster-api-provider-tencent/api/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*EndpointAccess)(nil), (*v1beta1.EndpointAccess)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_EndpointAccess_To_v1beta1_EndpointAccess(a.(*EndpointAccess), b.(*v1beta1.EndpointAccess), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.EndpointAccess)(nil), (*EndpointAccess)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EndpointAccess_To_v1alpha4_EndpointAccess(a.(*v1beta1.EndpointAccess), b.(*EndpointAccess), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKECluster)(nil), (*v1beta1.TKECluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKECluster_To_v1beta1_TKECluster(a.(*TKECluster), b.(*v1beta1.TKECluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKECluster)(nil), (*TKECluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKECluster_To_v1alpha4_TKECluster(a.(*v1beta1.TKECluster), b.(*TKECluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEClusterList)(nil), (*v1beta1.TKEClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEClusterList_To_v1beta1_TKEClusterList(a.(*TKEClusterList), b.(*v1beta1.TKEClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEClusterList)(nil), (*TKEClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEClusterList_To_v1alpha4_TKEClusterList(a.(*v1beta1.TKEClusterList), b.(*TKEClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEClusterSpec)(nil), (*v1beta1.TKEClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEClusterSpec_To_v1beta1_TKEClusterSpec(a.(*TKEClusterSpec), b.(*v1beta1.TKEClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEClusterSpec)(nil), (*TKEClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEClusterSpec_To_v1alpha4_TKEClusterSpec(a.(*v1beta1.TKEClusterSpec), b.(*TKEClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEClusterStatus)(nil), (*v1beta1.TKEClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEClusterStatus_To_v1beta1_TKEClusterStatus(a.(*TKEClusterStatus), b.(*v1beta1.TKEClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEClusterStatus)(nil), (*TKEClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEClusterStatus_To_v1alpha4_TKEClusterStatus(a.(*v1beta1.TKEClusterStatus), b.(*TKEClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEManagedMachinePool)(nil), (*v1beta1.TKEManagedMachinePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEManagedMachinePool_To_v1beta1_TKEManagedMachinePool(a.(*TKEManagedMachinePool), b.(*v1beta1.TKEManagedMachinePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEManagedMachinePool)(nil), (*TKEManagedMachinePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEManagedMachinePool_To_v1alpha4_TKEManagedMachinePool(a.(*v1beta1.TKEManagedMachinePool), b.(*TKEManagedMachinePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEManagedMachinePoolList)(nil), (*v1beta1.TKEManagedMachinePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEManagedMachinePoolList_To_v1beta1_TKEManagedMachinePoolList(a.(*TKEManagedMachinePoolList), b.(*v1beta1.TKEManagedMachinePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEManagedMachinePoolList)(nil), (*TKEManagedMachinePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEManagedMachinePoolList_To_v1alpha4_TKEManagedMachinePoolList(a.(*v1beta1.TKEManagedMachinePoolList), b.(*TKEManagedMachinePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEManagedMachinePoolSpec)(nil), (*v1beta1.TKEManagedMachinePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEManagedMachinePoolSpec_To_v1beta1_TKEManagedMachinePoolSpec(a.(*TKEManagedMachinePoolSpec), b.(*v1beta1.TKEManagedMachinePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEManagedMachinePoolSpec)(nil), (*TKEManagedMachinePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEManagedMachinePoolSpec_To_v1alpha4_TKEManagedMachinePoolSpec(a.(*v1beta1.TKEManagedMachinePoolSpec), b.(*TKEManagedMachinePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TKEManagedMachinePoolStatus)(nil), (*v1beta1.TKEManagedMachinePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_TKEManagedMachinePoolStatus_To_v1beta1_TKEManagedMachinePoolStatus(a.(*TKEManagedMachinePoolStatus), b.(*v1beta1.TKEManagedMachinePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.TKEManagedMachinePoolStatus)(nil), (*TKEManagedMachinePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TKEManagedMachinePoolStatus_To_v1alpha4_TKEManagedMachinePoolStatus(a.(*v1beta1.TKEManagedMachinePoolStatus), b.(*TKEManagedMachinePoolStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha4_EndpointAccess_To_v1beta1_EndpointAccess(in *EndpointAccess, out *v1beta1.EndpointAccess, s conversion.Scope) error {
	out.Public = (*bool)(unsafe.Pointer(in.Public))
	out.SecurityGroup = (*string)(unsafe.Pointer(in.SecurityGroup))
	out.Private = (*bool)(unsafe.Pointer(in.Private))
	out.SubnetID = (*string)(unsafe.Pointer(in.SubnetID))
	out.IsExtranet = (*bool)(unsafe.Pointer(in.IsExtranet))
	return nil
}

// Convert_v1alpha4_EndpointAccess_To_v1beta1_EndpointAccess is an autogenerated conversion function.
func Convert_v1alpha4_EndpointAccess_To_v1beta1_EndpointAccess(in *EndpointAccess, out *v1beta1.EndpointAccess, s conversion.Scope) error {
	return autoConvert_v1alpha4_EndpointAccess_To_v1beta1_EndpointAccess(in, out, s)
}

func autoConvert_v1beta1_EndpointAccess_To_v1alpha4_EndpointAccess(in *v1beta1.EndpointAccess, out *EndpointAccess, s conversion.Scope) error {
	out.Public = (*bool)(unsafe.Pointer(in.Public))
	out.SecurityGroup = (*string)(unsafe.Pointer(in.SecurityGroup))
	out.Private = (*bool)(unsafe.Pointer(in.Private))
	out.SubnetID = (*string)(unsafe.Pointer(in.SubnetID))
	out.IsExtranet = (*bool)(unsafe.Pointer(in.IsExtranet))
	return nil
}

// Convert_v1beta1_EndpointAccess_To_v1alpha4_EndpointAccess is an autogenerated conversion function.
func Convert_v1beta1_EndpointAccess_To_v1alpha4_EndpointAccess(in *v1beta1.EndpointAccess, out *EndpointAccess, s conversion.Scope) error {
	return autoConvert_v1beta1_EndpointAccess_To_v1alpha4_EndpointAccess(in, out, s)
}

func autoConvert_v1alpha4_TKECluster_To_v1beta1_TKECluster(in *TKECluster, out *v1beta1.TKECluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_TKEClusterSpec_To_v1beta1_TKEClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_TKEClusterStatus_To_v1beta1_TKEClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_TKECluster_To_v1beta1_TKECluster is an autogenerated conversion function.
func Convert_v1alpha4_TKECluster_To_v1beta1_TKECluster(in *TKECluster, out *v1beta1.TKECluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKECluster_To_v1beta1_TKECluster(in, out, s)
}

func autoConvert_v1beta1_TKECluster_To_v1alpha4_TKECluster(in *v1beta1.TKECluster, out *TKECluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TKEClusterSpec_To_v1alpha4_TKEClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TKEClusterStatus_To_v1alpha4_TKEClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TKECluster_To_v1alpha4_TKECluster is an autogenerated conversion function.
func Convert_v1beta1_TKECluster_To_v1alpha4_TKECluster(in *v1beta1.TKECluster, out *TKECluster, s conversion.Scope) error {
	return autoConvert_v1beta1_TKECluster_To_v1alpha4_TKECluster(in, out, s)
}

func autoConvert_v1alpha4_TKEClusterList_To_v1beta1_TKEClusterList(in *TKEClusterList, out *v1beta1.TKEClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.TKECluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_TKECluster_To_v1beta1_TKECluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_TKEClusterList_To_v1beta1_TKEClusterList is an autogenerated conversion function.
func Convert_v1alpha4_TKEClusterList_To_v1beta1_TKEClusterList(in *TKEClusterList, out *v1beta1.TKEClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEClusterList_To_v1beta1_TKEClusterList(in, out, s)
}

func autoConvert_v1beta1_TKEClusterList_To_v1alpha4_TKEClusterList(in *v1beta1.TKEClusterList, out *TKEClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TKECluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_TKECluster_To_v1alpha4_TKECluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_TKEClusterList_To_v1alpha4_TKEClusterList is an autogenerated conversion function.
func Convert_v1beta1_TKEClusterList_To_v1alpha4_TKEClusterList(in *v1beta1.TKEClusterList, out *TKEClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEClusterList_To_v1alpha4_TKEClusterList(in, out, s)
}

func autoConvert_v1alpha4_TKEClusterSpec_To_v1beta1_TKEClusterSpec(in *TKEClusterSpec, out *v1beta1.TKEClusterSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ClusterID = in.ClusterID
	out.Region = in.Region
	out.ClusterUUID = in.ClusterUUID
	out.ClusterVersion = (*string)(unsafe.Pointer(in.ClusterVersion))
	out.VPCID = in.VPCID
	out.OSName = in.OSName
	if err := apiv1alpha4.Convert_v1alpha4_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_EndpointAccess_To_v1beta1_EndpointAccess(&in.EndpointAccess, &out.EndpointAccess, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_TKEClusterSpec_To_v1beta1_TKEClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_TKEClusterSpec_To_v1beta1_TKEClusterSpec(in *TKEClusterSpec, out *v1beta1.TKEClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEClusterSpec_To_v1beta1_TKEClusterSpec(in, out, s)
}

func autoConvert_v1beta1_TKEClusterSpec_To_v1alpha4_TKEClusterSpec(in *v1beta1.TKEClusterSpec, out *TKEClusterSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ClusterID = in.ClusterID
	out.Region = in.Region
	out.ClusterUUID = in.ClusterUUID
	out.ClusterVersion = (*string)(unsafe.Pointer(in.ClusterVersion))
	out.VPCID = in.VPCID
	out.OSName = in.OSName
	if err := apiv1alpha4.Convert_v1beta1_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_EndpointAccess_To_v1alpha4_EndpointAccess(&in.EndpointAccess, &out.EndpointAccess, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TKEClusterSpec_To_v1alpha4_TKEClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_TKEClusterSpec_To_v1alpha4_TKEClusterSpec(in *v1beta1.TKEClusterSpec, out *TKEClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEClusterSpec_To_v1alpha4_TKEClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_TKEClusterStatus_To_v1beta1_TKEClusterStatus(in *TKEClusterStatus, out *v1beta1.TKEClusterStatus, s conversion.Scope) error {
	out.ExternalManagedControlPlane = (*bool)(unsafe.Pointer(in.ExternalManagedControlPlane))
	out.Ready = in.Ready
	out.Initialized = in.Initialized
	return nil
}

// Convert_v1alpha4_TKEClusterStatus_To_v1beta1_TKEClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_TKEClusterStatus_To_v1beta1_TKEClusterStatus(in *TKEClusterStatus, out *v1beta1.TKEClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEClusterStatus_To_v1beta1_TKEClusterStatus(in, out, s)
}

func autoConvert_v1beta1_TKEClusterStatus_To_v1alpha4_TKEClusterStatus(in *v1beta1.TKEClusterStatus, out *TKEClusterStatus, s conversion.Scope) error {
	out.ExternalManagedControlPlane = (*bool)(unsafe.Pointer(in.ExternalManagedControlPlane))
	out.Ready = in.Ready
	out.Initialized = in.Initialized
	return nil
}

// Convert_v1beta1_TKEClusterStatus_To_v1alpha4_TKEClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_TKEClusterStatus_To_v1alpha4_TKEClusterStatus(in *v1beta1.TKEClusterStatus, out *TKEClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEClusterStatus_To_v1alpha4_TKEClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_TKEManagedMachinePool_To_v1beta1_TKEManagedMachinePool(in *TKEManagedMachinePool, out *v1beta1.TKEManagedMachinePool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_TKEManagedMachinePoolSpec_To_v1beta1_TKEManagedMachinePoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_TKEManagedMachinePoolStatus_To_v1beta1_TKEManagedMachinePoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_TKEManagedMachinePool_To_v1beta1_TKEManagedMachinePool is an autogenerated conversion function.
func Convert_v1alpha4_TKEManagedMachinePool_To_v1beta1_TKEManagedMachinePool(in *TKEManagedMachinePool, out *v1beta1.TKEManagedMachinePool, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEManagedMachinePool_To_v1beta1_TKEManagedMachinePool(in, out, s)
}

func autoConvert_v1beta1_TKEManagedMachinePool_To_v1alpha4_TKEManagedMachinePool(in *v1beta1.TKEManagedMachinePool, out *TKEManagedMachinePool, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TKEManagedMachinePoolSpec_To_v1alpha4_TKEManagedMachinePoolSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TKEManagedMachinePoolStatus_To_v1alpha4_TKEManagedMachinePoolStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TKEManagedMachinePool_To_v1alpha4_TKEManagedMachinePool is an autogenerated conversion function.
func Convert_v1beta1_TKEManagedMachinePool_To_v1alpha4_TKEManagedMachinePool(in *v1beta1.TKEManagedMachinePool, out *TKEManagedMachinePool, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEManagedMachinePool_To_v1alpha4_TKEManagedMachinePool(in, out, s)
}

func autoConvert_v1alpha4_TKEManagedMachinePoolList_To_v1beta1_TKEManagedMachinePoolList(in *TKEManagedMachinePoolList, out *v1beta1.TKEManagedMachinePoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.TKEManagedMachinePool, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_TKEManagedMachinePool_To_v1beta1_TKEManagedMachinePool(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_TKEManagedMachinePoolList_To_v1beta1_TKEManagedMachinePoolList is an autogenerated conversion function.
func Convert_v1alpha4_TKEManagedMachinePoolList_To_v1beta1_TKEManagedMachinePoolList(in *TKEManagedMachinePoolList, out *v1beta1.TKEManagedMachinePoolList, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEManagedMachinePoolList_To_v1beta1_TKEManagedMachinePoolList(in, out, s)
}

func autoConvert_v1beta1_TKEManagedMachinePoolList_To_v1alpha4_TKEManagedMachinePoolList(in *v1beta1.TKEManagedMachinePoolList, out *TKEManagedMachinePoolList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TKEManagedMachinePool, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_TKEManagedMachinePool_To_v1alpha4_TKEManagedMachinePool(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_TKEManagedMachinePoolList_To_v1alpha4_TKEManagedMachinePoolList is an autogenerated conversion function.
func Convert_v1beta1_TKEManagedMachinePoolList_To_v1alpha4_TKEManagedMachinePoolList(in *v1beta1.TKEManagedMachinePoolList, out *TKEManagedMachinePoolList, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEManagedMachinePoolList_To_v1alpha4_TKEManagedMachinePoolList(in, out, s)
}

func autoConvert_v1alpha4_TKEManagedMachinePoolSpec_To_v1beta1_TKEManagedMachinePoolSpec(in *TKEManagedMachinePoolSpec, out *v1beta1.TKEManagedMachinePoolSpec, s conversion.Scope) error {
	out.MaxSize = in.MaxSize
	out.MinSize = in.MinSize
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.SecurityGroups = *(*[]string)(unsafe.Pointer(&in.SecurityGroups))
	out.ProviderIDList = *(*[]string)(unsafe.Pointer(&in.ProviderIDList))
	out.OSName = in.OSName
	out.InstanceType = in.InstanceType
	out.KeyIDs = *(*[]string)(unsafe.Pointer(&in.KeyIDs))
	return nil
}

// Convert_v1alpha4_TKEManagedMachinePoolSpec_To_v1beta1_TKEManagedMachinePoolSpec is an autogenerated conversion function.
func Convert_v1alpha4_TKEManagedMachinePoolSpec_To_v1beta1_TKEManagedMachinePoolSpec(in *TKEManagedMachinePoolSpec, out *v1beta1.TKEManagedMachinePoolSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEManagedMachinePoolSpec_To_v1beta1_TKEManagedMachinePoolSpec(in, out, s)
}

func autoConvert_v1beta1_TKEManagedMachinePoolSpec_To_v1alpha4_TKEManagedMachinePoolSpec(in *v1beta1.TKEManagedMachinePoolSpec, out *TKEManagedMachinePoolSpec, s conversion.Scope) error {
	out.MaxSize = in.MaxSize
	out.MinSize = in.MinSize
	out.SubnetIDs = *(*[]string)(unsafe.Pointer(&in.SubnetIDs))
	out.SecurityGroups = *(*[]string)(unsafe.Pointer(&in.SecurityGroups))
	out.ProviderIDList = *(*[]string)(unsafe.Pointer(&in.ProviderIDList))
	out.OSName = in.OSName
	out.InstanceType = in.InstanceType
	out.KeyIDs = *(*[]string)(unsafe.Pointer(&in.KeyIDs))
	return nil
}

// Convert_v1beta1_TKEManagedMachinePoolSpec_To_v1alpha4_TKEManagedMachinePoolSpec is an autogenerated conversion function.
func Convert_v1beta1_TKEManagedMachinePoolSpec_To_v1alpha4_TKEManagedMachinePoolSpec(in *v1beta1.TKEManagedMachinePoolSpec, out *TKEManagedMachinePoolSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEManagedMachinePoolSpec_To_v1alpha4_TKEManagedMachinePoolSpec(in, out, s)
}

func autoConvert_v1alpha4_TKEManagedMachinePoolStatus_To_v1beta1_TKEManagedMachinePoolStatus(in *TKEManagedMachinePoolStatus, out *v1beta1.TKEManagedMachinePoolStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			if err := apiv1alpha4.Convert_v1alpha4_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

// Convert_v1alpha4_TKEManagedMachinePoolStatus_To_v1beta1_TKEManagedMachinePoolStatus is an autogenerated conversion function.
func Convert_v1alpha4_TKEManagedMachinePoolStatus_To_v1beta1_TKEManagedMachinePoolStatus(in *TKEManagedMachinePoolStatus, out *v1beta1.TKEManagedMachinePoolStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_TKEManagedMachinePoolStatus_To_v1beta1_TKEManagedMachinePoolStatus(in, out, s)
}

func autoConvert_v1beta1_TKEManagedMachinePoolStatus_To_v1alpha4_TKEManagedMachinePoolStatus(in *v1beta1.TKEManagedMachinePoolStatus, out *TKEManagedMachinePoolStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Replicas = in.Replicas
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1alpha4.Conditions, len(*in))
		for i := range *in {
			if err := apiv1alpha4.Convert_v1beta1_Condition_To_v1alpha4_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

// Convert_v1beta1_TKEManagedMachinePoolStatus_To_v1alpha4_TKEManagedMachinePoolStatus is an autogenerated conversion function.
func Convert_v1beta1_TKEManagedMachinePoolStatus_To_v1alpha4_TKEManagedMachinePoolStatus(in *v1beta1.TKEManagedMachinePoolStatus, out *TKEManagedMachinePoolStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_TKEManagedMachinePoolStatus_To_v1alpha4_TKEManagedMachinePoolStatus(in, out, s)
}
