apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: sample-machinedeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerConfig:
        value:
          apiVersion: "tkeproviderconfig/v1alpha1"
          kind: "TKEMachineProviderConfig"
          zoneId: "800001"
          cpu: 1
          mem: 2
          bandwidthType: "PayByTraffic"
          bandwidth: 1
          subnetId: "subnet-ljftawon"
          storageSize: 50
          rootSize: 20
          password: "123456789!"
          isVpcGateway: 0
          wanIp: 1
          osName: "ubuntu16.04.1 LTSx86_64"
      versions:
        kubelet: 1.10.5
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "30%"
  minReadySeconds: 2
